# Site settings
title: Happier & Healthier You
header-img: img/start.jpg
# email:
copyright_name: Upper 90, LLC
description: "A behavior changed program, focused on helping individuals achieve health and happiness."
baseurl: ""
url: ""
# twitter_username: ditschfitness
# github_username:
# facebook_username:
# email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-107356668-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-feed]
